### ISSUE TITLE
Split Tunneling?

### ISSUE THREAD

**Issue by codewithtamim** [dev7dev/V2ray-Android#6]
How can I add split tunneling feature.

**Comment by dev7dev** [comment]
Hi,
Currently, this feature is available in the library.
If you take a look at [line 59 of the V2rayController class](https://github.com/dev7dev/V2ray-Android/blob/main/v2ray/src/main/java/dev/dev7/lib/v2ray/V2rayController.java#L59) you will see that in the last parameter, it receives a string array list called blocked_apps. By default, in this example, we send ‍‍`null` because we want all programs to pass through the tunnel.
You can put the package of any program that you don't want to pass through the tunnel in this array.

For example, I want the Chrome browser to not go through the tunnel and every site the user visits will see the user's real IP.

```

List<String> blocked_applications = new ArrayList<>();
blocked_applications.add("com.android.chrome");
V2rayController.StartV2ray(getApplicationContext(), "Default", v2ray_json_config.getText().toString(), blocked_applications);

```

**Comment by codewithtamim** [comment]
> Hi, Currently, this feature is available in the library. If you take a look at [line 59 of the V2rayController class](https://github.com/dev7dev/V2ray-Android/blob/main/v2ray/src/main/java/dev/dev7/lib/v2ray/V2rayController.java#L59) you will see that in the last parameter, it receives a string array list called blocked_apps. By default, in this example, we send ‍‍`null` because we want all programs to pass through the tunnel. You can put the package of any program that you don't want to pass through the tunnel in this array.
> 
> For example, I want the Chrome browser to not go through the tunnel and every site the user visits will see the user's real IP.
> 
> ```
> 
> List<String> blocked_applications = new ArrayList<>();
> blocked_applications.add("com.android.chrome");
> V2rayController.StartV2ray(getApplicationContext(), "Default", v2ray_json_config.getText().toString(), blocked_applications);
> ```

Thanks man !
